### PR TITLE
Protocol 3.4 support

### LINKED ISSUE #234: Add support for v3.2 protocol
Bonjour,

J'obtiens cette erreur au demarrage de gladys:

` TypeError: Cannot read property '1' of undefined
0|gladys   |     at _send.then.data (/home/pi/gladys/api/hooks/tuya/node_modules/tuyapi/index.js:123:41)
0|gladys   |     at <anonymous>
0|gladys   |     at process._tickDomainCallback (internal/process/next_tick.js:228:7)`

et des que j'actionne le device:

`0|gladys   | (node:18902) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): TypeError: Cannot read property '1' of undefined
0|gladys   | Tuya - Error, undefined device!
0|gladys   | Sending 500 ("Server Error") response:
0|gladys   |  Error: find() timed out. Is the device powered on and the ID or IP correct?
0|gladys   |     at pTimeout (/home/pi/gladys/api/hooks/tuya/node_modules/tuyapi/index.js:593:19)
0|gladys   |     at Timeout.setTimeout [as _onTimeout] (/home/pi/gladys/api/hooks/tuya/node_modules/p-timeout/index.js:20:13)
0|gladys   |     at ontimeout (timers.js:475:11)
0|gladys   |     at tryOnTimeout (timers.js:310:5)
0|gladys   |     at Timer.listOnTimeout (timers.js:270:5)
0|gladys   | Server Error:
0|gladys   |`

ligne 123 de tuyapi/index.js:
` resolve(data.dps['1']);`

J'utilise un smart switch:
SCW NF101

avec wireshark, je recupere:
 `ip":"192.168.1.xx","gwId":"bfx9268f215ecx78cdkpiv","active":2,"ablilty":0,"encrypt":true,"productKey":"zWxOK04ovOjw0Pxw","version":"3.2"}.B0`

Mes identifinats sont de cette forme:
`[ { id: 'bfx9268f215ecx78cdkpiv', key: 'b6a93451d8f07ga2' } ]`

des idees?

### LINKED ISSUE #481: Support protocol version 3.4
**Describe the bug**
I tried the example script from the read me. Tuyapi is able to find the device and to connect, but directly disconnects afterwards. It's not possible to keep the connection and listen to data. 

Also tried it in Node-Red with package node-red-contrib-tuya-smart-device which uses latest tuyapi. Same error, it constantly reconnects. But at least it receives some data events which results in error logs with messages like `Error: CRC mismatch: expected -674619356, was -22843090`

Maybe the problem is the protocol version 3.4? Didn't find any information if tuyapi supports 3.4.

debug output:
```
node test.js
  TuyAPI Finding missing IP undefined or ID bf97ae127518bd821b1mdo +0ms
  TuyAPI Received UDP message. +4s
  TuyAPI UDP data: +1ms
  TuyAPI {
  TuyAPI   payload: {
  TuyAPI     ip: '192.168.0.42',
  TuyAPI     gwId: 'bf97ae127518bd821b1mdo',
  TuyAPI     active: 2,
  TuyAPI     ablilty: 0,
  TuyAPI     encrypt: true,
  TuyAPI     productKey: 'keyyj3fy8x98arty',
  TuyAPI     version: '3.4',
  TuyAPI     token: true
  TuyAPI   },
  TuyAPI   leftover: false,
  TuyAPI   commandByte: 35,
  TuyAPI   sequenceN: 0
  TuyAPI } +1ms
  TuyAPI Connecting to 192.168.0.42... +5ms
  TuyAPI Socket connected. +7ms
Connected to device!
  TuyAPI GET Payload: +2ms
  TuyAPI {
  TuyAPI   gwId: 'bf97ae127518bd821b1mdo',
  TuyAPI   devId: 'bf97ae127518bd821b1mdo',
  TuyAPI   t: '1623446698',
  TuyAPI   dpId: [ 18, 19, 20 ],
  TuyAPI   uid: 'bf97ae127518bd821b1mdo'
  TuyAPI } +0ms
  TuyAPI GET Payload: +3ms
  TuyAPI {
  TuyAPI   gwId: 'bf97ae127518bd821b1mdo',
  TuyAPI   devId: 'bf97ae127518bd821b1mdo',
  TuyAPI   t: '1623446698',
  TuyAPI   dps: {},
  TuyAPI   uid: 'bf97ae127518bd821b1mdo'
  TuyAPI } +0ms
  TuyAPI Socket closed: 192.168.0.42 +13ms
  TuyAPI Disconnect +1ms
Disconnected from device.
```

### PR DESCRIPTION
**Pull request by Apollon77**
I catched the code from @harryzz repoditory where he posted that protocol 3.4 was implemented (see https://github.com/codetheweb/tuyapi/issues/481#issuecomment-985988646). I adjusted code style to the project one and reworked the code a bit to be less clustered when it comes to the 3.4 changes.
Additionally I added  a deferred promise for the "longer connect flow" to resolve the connect promise when the connection is really established.

This is completely untested! I hope that I get such a device tomorrow/tuesday, but if someone wants to : install from my Fork (https://github.com/Apollon77/tuyapi) and give it a shot. Ideally start with DEBUG=TuyAPI* and post your log when you tested it (successfuly or not) :-)

@codetheweb I will do a Draft PR for now, but if you have time please already have a look and tell me if you would like somethings to be adjusted.
I do not get any lint or tests running locally ... will try again, but if you have ideas....

fixes #234, fixes #481

### CODE REVIEW

**Comment by Apollon77** [comment]
@codetheweb Ok, lint and tests work now ... (and I adjusted a lot lint stuff)

**Comment by codetheweb** [comment]
Thanks for doing this! Just wanted to let you know I've been really busy the last few days but hope to take a look soon.

**Comment by Apollon77** [comment]
@codetheweb In the meantime I should also have a 3.4 device ... So plan is to try the changes out myself today

File: index.js [hunk 1]
```diff
@@ -439,6 +474,62 @@ class TuyaDevice extends EventEmitter {
     }
   }
 
+  /**
+   * Create a deferred promise that resolves as soon as the connection is established.
+   */
+  createDeferredConnectPromise() {
```
Comment (codetheweb) [inline index.js:480]: I don't think we need this, can we just return `new Promise()` at the end?

**Review by codetheweb — COMMENTED** [review]
Trusting that this all works since I don't have a device. :)

Tests pass locally for me 👍, not sure why they're not running on CI.

File: index.js (hunk 1 above)
Comment (Apollon77) [reply index.js:480]: The problem is that the 3.4 "connect" is in the end 3 messages exchanged, sothe final "resolve" will come from out an other method but we also still want to have "connect timeout" logic. So in the end for a "clean" solution we in any case need to store a promise.

The alternative is that we resolve connect promise already after we sent out the "start session exchange message", but in fact we are not yet connected.

**Comment by Apollon77** [comment]
For testing: I have one device and tested with this,but in the end no" long time testing" so far. I have also one more user using it - he had one time an issue that the devices went into a "restart loop", but honestly ... This could mean something is not 100%, but considering the quelity sometimes it must not mean anything ;-) And also after restarting problem did not re-occured till now.

So I would consider as ok aka "best we can say for now" :-)

**Comment by Apollon77** [comment]
@codetheweb Lets wait a day longer ... On user that tried this has oissues, so I now started a bit a "Long time test" ... lets see if it is stable for me

**Comment by Apollon77** [comment]
@codetheweb Ok I would go and release this. In fact it works. I only have one device to verify and yes this device closes the connection every 2-3h, but a reconnect works after 30 or latest second try after 60s ... but from all the quality issues we know from Tuya devices this is not enough to proof it a "protocol implementation issue" (and also python lib do not have anything else). So best it can be right now

File: index.js (hunk 1 above)
Comment (codetheweb) [reply index.js:480]: Right, I agree we need to store a Promise, just not sure why we need to have this wrapper that doesn't seem to have any custom logic to create one.

Comment (Apollon77) [reply index.js:480]: This wrapper is needed because you can not just store the two methods reject and resolve... I experimented around a long time on how to build a deferred promise and this solution is used in one of my other projects and originally came from an other developer that uses it in his projects.

In fact if you return a promise you have no real way to reference to the reject or resolve method of this object "outside" of the Promise constructor. Thats why this is the trick to allow this.

It cost me hours to come to this in my other project :-)

You find it also here e.g. https://www.getrevue.co/profile/masteringjs/issues/promises-and-the-deferred-antipattern-235313

Comment (Apollon77) [reply index.js:480]: (and I decided against adding a dependency lib to get a Deffered option which is kind of just doing exactly also that - e.g. https://github.com/ljharb/promise-deferred/blob/main/index.js

Comment (Apollon77) [reply index.js:480]: PS: If you mean that I should kill the extra function and directly integrate the code into the connect function then yes I can do this. ;-)

Comment (codetheweb) [reply index.js:480]: Read the code again and I understand the issue now, seems ok for now.

**Review by codetheweb — APPROVED** [review]

**Comment by codetheweb** [comment]
Published in v7.5.0.

**Comment by Apollon77** [comment]
Thank you very much!
